Traceback (most recent call last):
  File "/opt/anaconda3/envs/SLI39/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/anaconda3/envs/SLI39/lib/python3.9/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/anaconda3/envs/SLI39/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/anaconda3/envs/SLI39/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/anaconda3/envs/SLI39/lib/python3.9/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/anaconda3/envs/SLI39/lib/python3.9/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/anaconda3/envs/SLI39/lib/python3.9/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
climateIndex = ['AO','AAO','BEST','DMI','ONI','PDO','PMM','PNA','TNA']

# get list of all directories in dirs['model_output_dir']
dirs_list = os.listdir(dirs['model_output_dir'])

# only keep the directories that are numbers
recordIDs = [int(d) for d in dirs_list if d.isdigit()]

# remove 57
# recordIDs.remove(57)

# get station names from the best_params.json files
station_names = {}
for recordID in recordIDs:
    jsonpath = Path(dirs['model_output_dir']) / str(recordID) / 'best_params.json'
    with open(jsonpath, 'r') as f:
        output = json.load(f)
        station_names[recordID] = output['modelInfo']['station_name']

# sort the station names by the recordID
station_names = {k: v for k, v in sorted(station_names.items(), key=lambda item: item[0])}

station_names
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [0;32mIn[2], line 4[0m
[1;32m      1[0m climateIndex [38;5;241m=[39m [[38;5;124m'[39m[38;5;124mAO[39m[38;5;124m'[39m,[38;5;124m'[39m[38;5;124mAAO[39m[38;5;124m'[39m,[38;5;124m'[39m[38;5;124mBEST[39m[38;5;124m'[39m,[38;5;124m'[39m[38;5;124mDMI[39m[38;5;124m'[39m,[38;5;124m'[39m[38;5;124mONI[39m[38;5;124m'[39m,[38;5;124m'[39m[38;5;124mPDO[39m[38;5;124m'[39m,[38;5;124m'[39m[38;5;124mPMM[39m[38;5;124m'[39m,[38;5;124m'[39m[38;5;124mPNA[39m[38;5;124m'[39m,[38;5;124m'[39m[38;5;124mTNA[39m[38;5;124m'[39m]
[1;32m      3[0m [38;5;66;03m# get list of all directories in dirs['model_output_dir'][39;00m
[0;32m----> 4[0m dirs_list [38;5;241m=[39m [43mos[49m[38;5;241;43m.[39;49m[43mlistdir[49m[43m([49m[43mdirs[49m[43m[[49m[38;5;124;43m'[39;49m[38;5;124;43mmodel_output_dir[39;49m[38;5;124;43m'[39;49m[43m][49m[43m)[49m
[1;32m      6[0m [38;5;66;03m# only keep the directories that are numbers[39;00m
[1;32m      7[0m recordIDs [38;5;241m=[39m [[38;5;28mint[39m(d) [38;5;28;01mfor[39;00m d [38;5;129;01min[39;00m dirs_list [38;5;28;01mif[39;00m d[38;5;241m.[39misdigit()]

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '/Users/jfiedler/Documents/Repositories/SL_Hawaii/SL_Hawaii/data/GEV_model_output'

