Traceback (most recent call last):
  File "/opt/anaconda3/envs/SLI39/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/anaconda3/envs/SLI39/lib/python3.9/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/anaconda3/envs/SLI39/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/anaconda3/envs/SLI39/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/anaconda3/envs/SLI39/lib/python3.9/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/anaconda3/envs/SLI39/lib/python3.9/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/anaconda3/envs/SLI39/lib/python3.9/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Create a dictionary to store GEV parameters for each category
gev_params = {}

for category, group in grouped_data:
    # Extract height data
    heights = group['height'].values
    
    # Fit GEV distribution
    c, loc, scale = genextreme.fit(heights)
    
    # Store parameters
    gev_params[category] = (c, loc, scale)

    print(f"GEV parameters for {category} category: c={c:.4f}, loc={loc:.4f}, scale={scale:.4f}")
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[23], line 9[0m
[1;32m      6[0m heights [38;5;241m=[39m group[[38;5;124m'[39m[38;5;124mheight[39m[38;5;124m'[39m][38;5;241m.[39mvalues
[1;32m      8[0m [38;5;66;03m# Fit GEV distribution[39;00m
[0;32m----> 9[0m c, loc, scale [38;5;241m=[39m [43mgenextreme[49m[38;5;241m.[39mfit(heights)
[1;32m     11[0m [38;5;66;03m# Store parameters[39;00m
[1;32m     12[0m gev_params[category] [38;5;241m=[39m (c, loc, scale)

[0;31mNameError[0m: name 'genextreme' is not defined

