Traceback (most recent call last):
  File "/Users/juliafiedler/anaconda3/envs/SLI39/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/juliafiedler/anaconda3/envs/SLI39/lib/python3.9/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/juliafiedler/anaconda3/envs/SLI39/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/juliafiedler/anaconda3/envs/SLI39/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/juliafiedler/anaconda3/envs/SLI39/lib/python3.9/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/juliafiedler/anaconda3/envs/SLI39/lib/python3.9/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/juliafiedler/anaconda3/envs/SLI39/lib/python3.9/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# remove long-term trend from rsl_monthly
trend_mag_rsl, trend_line_rsl, trend_rate_rsl = process_trend_with_nan(rsl_monthly.sea_level)

rsl_monthly_detrended = rsl_monthly.sea_level - trend_line_rsl

# add detrended rsl_monthly to rsl_monthly
rsl_monthly['sea_level_detrended'] = rsl_monthly_detrended
rsl_monthly['sea_level_detrended'].attrs = {'long_name': 'sea level anomaly', 'units': 'm'}
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[13], line 2[0m
[1;32m      1[0m [38;5;66;03m# remove long-term trend from rsl_monthly[39;00m
[0;32m----> 2[0m trend_mag_rsl, trend_line_rsl, trend_rate_rsl [38;5;241m=[39m process_trend_with_nan([43mrsl_monthly[49m[38;5;241;43m.[39;49m[43msea_level[49m)
[1;32m      4[0m rsl_monthly_detrended [38;5;241m=[39m rsl_monthly[38;5;241m.[39msea_level [38;5;241m-[39m trend_line_rsl
[1;32m      6[0m [38;5;66;03m# add detrended rsl_monthly to rsl_monthly[39;00m

File [0;32m~/anaconda3/envs/SLI39/lib/python3.9/site-packages/xarray/core/common.py:278[0m, in [0;36mAttrAccessMixin.__getattr__[0;34m(self, name)[0m
[1;32m    276[0m         [38;5;28;01mwith[39;00m suppress([38;5;167;01mKeyError[39;00m):
[1;32m    277[0m             [38;5;28;01mreturn[39;00m source[name]
[0;32m--> 278[0m [38;5;28;01mraise[39;00m [38;5;167;01mAttributeError[39;00m(
[1;32m    279[0m     [38;5;124mf[39m[38;5;124m"[39m[38;5;132;01m{[39;00m[38;5;28mtype[39m([38;5;28mself[39m)[38;5;241m.[39m[38;5;18m__name__[39m[38;5;132;01m!r}[39;00m[38;5;124m object has no attribute [39m[38;5;132;01m{[39;00mname[38;5;132;01m!r}[39;00m[38;5;124m"[39m
[1;32m    280[0m )

[0;31mAttributeError[0m: 'Dataset' object has no attribute 'sea_level'

