Traceback (most recent call last):
  File "/Users/juliafiedler/anaconda3/envs/SLI39/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/juliafiedler/anaconda3/envs/SLI39/lib/python3.9/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/juliafiedler/anaconda3/envs/SLI39/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/juliafiedler/anaconda3/envs/SLI39/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/juliafiedler/anaconda3/envs/SLI39/lib/python3.9/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/juliafiedler/anaconda3/envs/SLI39/lib/python3.9/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/juliafiedler/anaconda3/envs/SLI39/lib/python3.9/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# remove the linear trend from rsl_daily

trend_mag, trend_line, trend_rate = process_trend_with_nan(rsl_daily['rsl_mhhw'])

rsl_daily['rsl_mhhw_detrended'] = rsl_daily['rsl_mhhw'] - trend_line

rsl_daily['rsl_mhhw_detrended'].sel(record_id = 590).plot()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[2], line 3[0m
[1;32m      1[0m [38;5;66;03m# remove the linear trend from rsl_daily[39;00m
[0;32m----> 3[0m trend_mag, trend_line, trend_rate [38;5;241m=[39m [43mprocess_trend_with_nan[49m(rsl_daily[[38;5;124m'[39m[38;5;124mrsl_mhhw[39m[38;5;124m'[39m])
[1;32m      5[0m rsl_daily[[38;5;124m'[39m[38;5;124mrsl_mhhw_detrended[39m[38;5;124m'[39m] [38;5;241m=[39m rsl_daily[[38;5;124m'[39m[38;5;124mrsl_mhhw[39m[38;5;124m'[39m] [38;5;241m-[39m trend_line
[1;32m      7[0m rsl_daily[[38;5;124m'[39m[38;5;124mrsl_mhhw_detrended[39m[38;5;124m'[39m][38;5;241m.[39msel(record_id [38;5;241m=[39m [38;5;241m590[39m)[38;5;241m.[39mplot()

[0;31mNameError[0m: name 'process_trend_with_nan' is not defined

